### ISSUE TITLE
Import bill details from the openstates API

### ISSUE THREAD

**Issue by wzrad** [legislated/legislated-api#7]
It probably makes sense to convert the `ImportBillDetails` to hit the openstates API rather than scrape the ilga.gov site.

If their API allows fetching details for multiple bills by id / document number simultaneously, we could fire off a single bill details job for all the bills in a hearing. That would significantly reduce the number of workers we spin up.

We should source the summary there and pull in a few extra fields like type, session, and probably sponsors per #4. Session should be a new entity. We shouldn't name the bill field `type` because it screws with ActiveRecord STI (I've been using `kind` instead).

**Comment by wontruefree** [comment]
I thought openstates went away.  Is this the same people as before?

**Comment by wontruefree** [comment]
I do not see a way to get witness slips yet.
we could get all the data from open state and just do scrapping for the witness slips instead of all the other data.

**Comment by justgosh** [comment]
Openstates.org are the programmers from the sunlightfoundation.com  They did not build their product with a customer in mind so their product isn't a complete vision.  They offer access to data through their API from the state websites they have scraped.  Openstates is scraping www.ilga.gov but they are not scraping my.ilga.gov (witness slips).  They are working on scraping my.ilga.gov but one of the openstates tickets involving my.ilga.gov was just closed and not reassigned because someone was quitting the project, so it's unclear if they are going to pursue scraping my.ilga.gov witness slip data any time soon.

**Comment by wontruefree** [comment]
That makes a lot of sense.
Thanks for the info
